//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingYearSubInfo
    {
        public int Id { get; set; }
        public string StartingDate { get; set; }
        public string EndingDate { get; set; }
        public string Period { get; set; }
        public bool Locked { get; set; }
        public int AccountingYearId { get; set; }
    }
}
