//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvgGreyConsFabricCost
    {
        public int Id { get; set; }
        public Nullable<int> PrecostingId { get; set; }
        public Nullable<int> FebricCostId { get; set; }
        public string PoNo { get; set; }
        public string Color { get; set; }
        public Nullable<double> GmtsSizes { get; set; }
        public Nullable<double> Dia { get; set; }
        public Nullable<double> ItemSizes { get; set; }
        public Nullable<double> FinishCons { get; set; }
        public Nullable<double> ProcessLoss { get; set; }
        public Nullable<double> GreyCons { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Pcs { get; set; }
        public Nullable<double> TotalQty { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string Remarks { get; set; }
    }
}
