//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankInfo
    {
        public int Id { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string BankCode { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string SwiftCode { get; set; }
        public string WebSite { get; set; }
        public string ContactPerson { get; set; }
        public string PhoneNo { get; set; }
        public string LienBank { get; set; }
        public string IssuingBank { get; set; }
        public string SalaryBank { get; set; }
        public string AdvisingBank { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
    }
}
