//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodyPartEntry
    {
        public int Id { get; set; }
        public string BodyPartFullName { get; set; }
        public string BodyPartShortName { get; set; }
        public string EntryPages { get; set; }
        public string BodyPartType { get; set; }
        public string status { get; set; }
    }
}
