//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTBOrImportLCInvoiceDetail
    {
        public int Id { get; set; }
        public int BtbOrMarginLcMasterId { get; set; }
        public string LCNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public int IssuingBank { get; set; }
        public string InvoiceDate { get; set; }
        public string DocumentValue { get; set; }
        public double LCValue { get; set; }
        public int LCCurrency { get; set; }
        public string ShipmentDate { get; set; }
        public string CompanyAccDate { get; set; }
        public int SupplierId { get; set; }
        public string BankAccDate { get; set; }
        public string BankRef { get; set; }
        public int Importer { get; set; }
        public string AcceptanceTime { get; set; }
        public string RetireSource { get; set; }
        public string PayTerm { get; set; }
        public string EDFTenor { get; set; }
        public string Remarks { get; set; }
        public string LCType { get; set; }
        public double ExchangeRate { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
