//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityCalculation
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string CapacitySource { get; set; }
        public int Location { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public double ManOrMachinePerLine { get; set; }
        public double BasicSAM { get; set; }
        public double Efficiency { get; set; }
        public string FinType { get; set; }
        public double Smv { get; set; }
        public double WoHrs { get; set; }
    }
}
