//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityAllocation
    {
        public int Id { get; set; }
        public int Company { get; set; }
        public int Location { get; set; }
        public int YearId { get; set; }
        public int MonthId { get; set; }
    }
}
