//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartoonMeasurmentTrimsCon
    {
        public int Id { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public int TrimsCostId { get; set; }
        public Nullable<int> TrimsConsId { get; set; }
        public string Style { get; set; }
        public string Description { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public string Cm { get; set; }
        public Nullable<double> Ply { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string TermsNconditions { get; set; }
        public Nullable<double> Hight { get; set; }
        public Nullable<int> PrecostingId { get; set; }
    }
}
