//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommersialCommissionCost
    {
        public int Id { get; set; }
        public Nullable<int> BtbId { get; set; }
        public Nullable<int> CommissionName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifyiedDate { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
