//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommercialJobSelectionView
    {
        public int ordAutoId { get; set; }
        public Nullable<int> PoDetId { get; set; }
        public string JobNo { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ItemName { get; set; }
        public string BuyerName { get; set; }
        public string StyleRefNo { get; set; }
        public string Style_Description { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public int ordUomId { get; set; }
        public string UomName { get; set; }
        public int CompanyId { get; set; }
        public double Smv { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<double> JobQty { get; set; }
        public string PoNumber { get; set; }
        public Nullable<double> PoQuantity { get; set; }
        public Nullable<double> AvgPrice { get; set; }
        public string ShipmentDate { get; set; }
        public string itemDtlsId { get; set; }
        public string FileNo { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string CostingDate { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string TeamLeaderName { get; set; }
        public string DealingMerchantName { get; set; }
        public Nullable<int> DealingMerchanId { get; set; }
        public int isSelected { get; set; }
        public Nullable<double> JobQuantity { get; set; }
        public Nullable<double> AvgUnitPrice { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> PrecostingId { get; set; }
    }
}
