//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionCostForPreCost
    {
        public int Id { get; set; }
        public int PrecostingId { get; set; }
        public int FabricDescriptionId { get; set; }
        public int PoNo { get; set; }
        public int ProcessId { get; set; }
        public double ProcessLoss { get; set; }
        public double ReqQty { get; set; }
        public double AvgReqQty { get; set; }
        public double ChargeUnit { get; set; }
        public double Amount { get; set; }
        public string Status { get; set; }
        public Nullable<int> FabricCostId { get; set; }
        public Nullable<double> FabricCons { get; set; }
    }
}
