//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostComponenetsMasterDetail
    {
        public int Id { get; set; }
        public int CostComponetId { get; set; }
        public int PreCostingId { get; set; }
        public string CostComponentName { get; set; }
        public Nullable<double> BudgetedCost { get; set; }
        public Nullable<double> QPrice { get; set; }
    }
}
