//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutandLaydetail
    {
        public int Id { get; set; }
        public int PoId { get; set; }
        public double OrderCutNo { get; set; }
        public string ShipDate { get; set; }
        public int GarmentsItemId { get; set; }
        public string GarmentsColor { get; set; }
        public string Plies { get; set; }
        public double SizeRatio { get; set; }
        public double MarkerQnty { get; set; }
        public double Orderqty { get; set; }
        public double TotalLayqty { get; set; }
        public double Laybalanceqty { get; set; }
        public double CutandLayEntryMasterId { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
