//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepoLocationMapping
    {
        public int Id { get; set; }
        public int CountryId { get; set; }
        public int UltimateCountryId { get; set; }
        public string CountryDepoName { get; set; }
        public string status { get; set; }
    }
}
