//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionProfile
    {
        public int Id { get; set; }
        public string DivisionName { get; set; }
        public string ShortName { get; set; }
        public int CompanyName { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string Remark { get; set; }
        public int CountryId { get; set; }
        public string Website { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
    }
}
