//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocSubmissiontoBankInvoiceList
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public Nullable<int> Sl { get; set; }
        public string InvoiceNo { get; set; }
        public string LcOrSCNo { get; set; }
        public string BLNo { get; set; }
        public string InvoiceDate { get; set; }
        public double NetInvValue { get; set; }
        public string OrderNumbers { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
