//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocSubmissiontoBuyer
    {
        public int Id { get; set; }
        public string SystemID { get; set; }
        public int CompanyNameID { get; set; }
        public int BuyerId { get; set; }
        public string SalesContractNo { get; set; }
        public string SubmissionDate { get; set; }
        public double DaystoRealize { get; set; }
        public string PossibleRealiDate { get; set; }
        public string CourierCompany { get; set; }
        public string GsPCourierDate { get; set; }
        public string CourierReceiptNo { get; set; }
        public int LienBankId { get; set; }
        public int LcOrSCCurrencyId { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
        public string ExportIds { get; set; }
    }
}
