//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DyeingAndFinishingCharge
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string ConstCompo { get; set; }
        public string ProcessType { get; set; }
        public string ProcessName { get; set; }
        public string Color { get; set; }
        public string WidthDiatype { get; set; }
        public string InHouseRate { get; set; }
        public int UOMId { get; set; }
        public string Ratetype { get; set; }
        public string CustomerRate { get; set; }
        public string SubconBuyer { get; set; }
        public string Status { get; set; }
    }
}
