//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EfficiencyPercentageSlab
    {
        public int Id { get; set; }
        public double LowerLimitForSMVRange { get; set; }
        public double UpperLimitForSMVRange { get; set; }
        public double LowerLimitForOrderQty { get; set; }
        public double UpperLimitForOrderQty { get; set; }
        public double NewOrderForEfficiency { get; set; }
        public double RepeatOrderForEfficiency { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
