//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmbellishmentCost
    {
        public int Id { get; set; }
        public int PrecostingId { get; set; }
        public string EmbelName { get; set; }
        public int EmbelTypeId { get; set; }
        public int BodyPartId { get; set; }
        public int CountryId { get; set; }
        public int SupplierId { get; set; }
        public double Cons { get; set; }
        public double Amount { get; set; }
        public double Rate { get; set; }
        public string Status { get; set; }
        public bool IsEmbellishmentCostBooking { get; set; }
        public Nullable<long> IndexNo { get; set; }
        public string ReportType { get; set; }
    }
}
