//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErpImage
    {
        public int Id { get; set; }
        public int PageId { get; set; }
        public int PageSpecificationId { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
    }
}
