//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportLCAmendmentDetail
    {
        public int Id { get; set; }
        public int ExportLCAmendmentMasterId { get; set; }
        public string AccPONo { get; set; }
        public string OrderNumber { get; set; }
        public double OrderQty { get; set; }
        public double OrderValue { get; set; }
        public double AttachQty { get; set; }
        public double Rate { get; set; }
        public double AttachVal { get; set; }
        public string StyleRef { get; set; }
        public string Item { get; set; }
        public string JobNo { get; set; }
        public string FabricDescription { get; set; }
        public string Categroy { get; set; }
        public string HsCode { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
