//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportInformationDetailsSub
    {
        public int Id { get; set; }
        public double InvoiceValue { get; set; }
        public int ExportInvoiceId { get; set; }
        public string AdditionalInfo { get; set; }
        public double Discount { get; set; }
        public double DiscountAmount { get; set; }
        public double AnnualBonus { get; set; }
        public double BonusAmount { get; set; }
        public double Claim { get; set; }
        public double ClaimAmount { get; set; }
        public double InvoiceQuantity { get; set; }
        public double Commission { get; set; }
        public double CommissionAmount { get; set; }
        public double OtherDeduction { get; set; }
        public double OtherDedAmnt { get; set; }
        public double AddUpcharge { get; set; }
        public double NetInvoiceValue { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
