//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportProceedsRealization
    {
        public int Id { get; set; }
        public string SystemId { get; set; }
        public int Beneficiary { get; set; }
        public int Buyer { get; set; }
        public string BillOrInvoiceNo { get; set; }
        public string ReceivedDate { get; set; }
        public string LcOrSCNo { get; set; }
        public int CurrencyId { get; set; }
        public string BillOrInvoiceDate { get; set; }
        public double BillOrInvoiceAmount { get; set; }
        public double NegotiatedAmount { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
        public int BillOrInvoiceId { get; set; }
    }
}
