//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportInformationDetail
    {
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public string JobNo { get; set; }
        public int JobNoId { get; set; }
        public int OrderId { get; set; }
        public int ExportInformationId { get; set; }
        public string StyleRef { get; set; }
        public string ArticleNo { get; set; }
        public string ShipmentDate { get; set; }
        public double AttachedOrderQnty { get; set; }
        public string Uom { get; set; }
        public double Rate { get; set; }
        public double CurrInvoiceQnty { get; set; }
        public double CurrInvoiceValue { get; set; }
        public double CumuInvoiceQnty { get; set; }
        public double PoBalanceQnty { get; set; }
        public double CumuInvoiceValue { get; set; }
        public double ExFactoryQnty { get; set; }
        public string Merchandiser { get; set; }
        public string ProductionSource { get; set; }
        public string Brand { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
