//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricServiceBooking
    {
        public int Id { get; set; }
        public int BookingMonth { get; set; }
        public int BookingYear { get; set; }
        public string BookingNo { get; set; }
        public string OrderNo { get; set; }
        public string JobNo { get; set; }
        public int BuyerProfileId { get; set; }
        public int CurrencyId { get; set; }
        public int ExchangeRate { get; set; }
        public string BookingDate { get; set; }
        public string DeliveryDate { get; set; }
        public string PayMode { get; set; }
        public string Source { get; set; }
        public string SupplierName { get; set; }
        public string Attention { get; set; }
        public int FabricDescriptionId { get; set; }
        public int Process { get; set; }
        public string Sensitivity { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
