//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricDesPreCost
    {
        public int Id { get; set; }
        public string FabNature { get; set; }
        public string Construction { get; set; }
        public Nullable<double> GsmWeight { get; set; }
        public string ColorRange { get; set; }
        public Nullable<double> StichLength { get; set; }
        public Nullable<double> ProcessLoss { get; set; }
        public string Composition { get; set; }
        public string FabricDescriptionDetails { get; set; }
    }
}
