//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricColorSensitivity
    {
        public int Id { get; set; }
        public int FabricId { get; set; }
        public string Color { get; set; }
        public string ContrastColor { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> PrecostingId { get; set; }
        public Nullable<int> FabricIndexNo { get; set; }
    }
}
