//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialParameterSetup
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string ApplyingPeriod { get; set; }
        public string To { get; set; }
        public double BEPCM { get; set; }
        public double AskingCM { get; set; }
        public double AskingProfit { get; set; }
        public double NoOfFactoryMachine { get; set; }
        public double MonthlyCMExpense { get; set; }
        public double WorkingHour { get; set; }
        public double CostPerMinute { get; set; }
        public double ActualCM { get; set; }
        public double AskingAVGRate { get; set; }
        public string Status { get; set; }
        public double MaxProfi { get; set; }
        public double DepreciationAndAmortization { get; set; }
        public double InterestExpenses { get; set; }
        public double IncomeTax { get; set; }
        public double OperatingExpenses { get; set; }
    }
}
