//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishFabricRollReceiveByStore
    {
        public int Id { get; set; }
        public string ReceiveNo { get; set; }
        public string ChallanNo { get; set; }
        public string ReceiveDate { get; set; }
        public int CompanyId { get; set; }
        public string ProdSource { get; set; }
        public int DyeFinishCompany { get; set; }
        public int LocationId { get; set; }
        public string StoreName { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
