//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarmentsItemEntry
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public string CommercialName { get; set; }
        public int ProductCategoryId { get; set; }
        public int ProductTypeId { get; set; }
        public Nullable<double> StandardSMV { get; set; }
        public Nullable<double> Efficiency { get; set; }
        public string Status { get; set; }
    }
}
