//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreyFabricTransferEntryItemInfo
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public string FromStore { get; set; }
        public string ToStore { get; set; }
        public string ItemDescription { get; set; }
        public string YarnLot { get; set; }
        public double TransferedQnty { get; set; }
        public string YarnBrand { get; set; }
        public string BtbSelection { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
