//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportDocAcceptanceNonLCForShipDtl
    {
        public int Id { get; set; }
        public string BlOrCargoNo { get; set; }
        public string BlOrCargoDate { get; set; }
        public int ShipmentModeId { get; set; }
        public string DocumentStatus { get; set; }
        public string CopyDocReceiveDate { get; set; }
        public string OriginalDocReceiveDate { get; set; }
        public string DocumenttoCAndF { get; set; }
        public string FeederVessel { get; set; }
        public string MotherVessel { get; set; }
        public string EtaDate { get; set; }
        public string IcReceivedDate { get; set; }
        public string ShippingBillNo { get; set; }
        public string Incoterm { get; set; }
        public string IncotermPlace { get; set; }
        public string PortofLoading { get; set; }
        public string PortofDischarge { get; set; }
        public string InternalFileNo { get; set; }
        public string BillOfEntryNo { get; set; }
        public string PsiReferenceNo { get; set; }
        public string MaturityDate { get; set; }
        public string BillOfEntryDate { get; set; }
        public double PakgQuantity { get; set; }
        public string PakgQuantityDescription { get; set; }
        public string EdfPaidDate { get; set; }
        public string ContainerNo { get; set; }
        public string ClickTOAddFile { get; set; }
        public int ImportDocAcceptanceNonLCMasterId { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
