//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportPaymentEntry
    {
        public int Id { get; set; }
        public string PaymentHead { get; set; }
        public string AdjSource { get; set; }
        public string AdjSourceRef { get; set; }
        public double ConversionRate { get; set; }
        public double AcceptedAmount { get; set; }
        public string InvoicebalanceValue { get; set; }
        public string DomCurrency { get; set; }
        public string Remarks { get; set; }
        public string ClickToAddFile { get; set; }
        public int ImportPaymentMasterId { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
