//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputPannelPodetail
    {
        public int Input_Pannel_ID { get; set; }
        public Nullable<int> Po_details_ID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Country_Type { get; set; }
        public string Cutt_off_Date { get; set; }
        public string Cutt_off { get; set; }
        public string Country_Shipment_date { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Packing_ID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Amount { get; set; }
        public string EntryDate { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<int> Uom { get; set; }
    }
}
