//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuedNewItem
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public string ProgramNo { get; set; }
        public string StoreName { get; set; }
        public double NoOfRoll { get; set; }
        public string ItemDescription { get; set; }
        public double IssueQuantity { get; set; }
        public string FabricColor { get; set; }
        public string StitchLength { get; set; }
        public string YarnLot { get; set; }
        public string YarnCount { get; set; }
        public string Rack { get; set; }
        public string Shelf { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
