//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAccountCreation
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int ItemCategoryId { get; set; }
        public int ItemGroupId { get; set; }
        public string SubGroupCode { get; set; }
        public string SubGroupName { get; set; }
        public string ItemCode { get; set; }
        public string ItemDescription { get; set; }
        public string ItemSize { get; set; }
        public string ReOrderLabel { get; set; }
        public string MinLabel { get; set; }
        public string MaxLabel { get; set; }
        public string OrderUom { get; set; }
        public string ConsUom { get; set; }
        public string ItemAccount { get; set; }
        public string Status { get; set; }
        public string Brand { get; set; }
        public int OriginOrCountryId { get; set; }
        public string Model { get; set; }
    }
}
