//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetailsOrderEntry
    {
        public int id { get; set; }
        public Nullable<int> order_entry_id { get; set; }
        public string item { get; set; }
        public Nullable<double> ratio { get; set; }
        public Nullable<double> sew_smv_pcs { get; set; }
        public Nullable<double> cut_smv_pcs { get; set; }
        public Nullable<double> fin_smv_pcs { get; set; }
        public string complexity { get; set; }
        public string print { get; set; }
        public string embro_yes_no { get; set; }
        public Nullable<double> embro_number { get; set; }
        public string wash_yes_no { get; set; }
        public Nullable<double> wash_number { get; set; }
        public string sp_works_yes_no { get; set; }
        public Nullable<double> sp_works_number { get; set; }
        public string gmts_dyeing_yes_no { get; set; }
        public Nullable<double> gmts_dyeing_number { get; set; }
        public string aop_yes_no { get; set; }
        public Nullable<double> aop_number { get; set; }
    }
}
