//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemGroup
    {
        public int Id { get; set; }
        public int ItemCategoryId { get; set; }
        public string GroupCode { get; set; }
        public string ItemGroupName { get; set; }
        public string ItemType { get; set; }
        public string OrderUom { get; set; }
        public string ConsUom { get; set; }
        public Nullable<double> ConvFactor { get; set; }
        public string FancyItem { get; set; }
        public string CalParameter { get; set; }
        public string status { get; set; }
    }
}
