//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnitGreyFabricIssueReturn
    {
        public int Id { get; set; }
        public string ReturnNumber { get; set; }
        public int CompanyName { get; set; }
        public string Basis { get; set; }
        public string FBookingReqsnNo { get; set; }
        public int Location { get; set; }
        public string ReturnSource { get; set; }
        public int KnittingCompany { get; set; }
        public string ReturnDate { get; set; }
        public string ReturnChallan { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
