//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnittingCharge
    {
        public int Id { get; set; }
        public int CompanyName { get; set; }
        public int BodyPartId { get; set; }
        public string ConstructionComposition { get; set; }
        public string GSM { get; set; }
        public string Gauge { get; set; }
        public string YarnDescription { get; set; }
        public int InHouseRate { get; set; }
        public string CustomerRate { get; set; }
        public string SubconBuyer { get; set; }
        public int UOMId { get; set; }
        public string Status { get; set; }
    }
}
