//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTestRateChart
    {
        public int Id { get; set; }
        public string TestCatagory { get; set; }
        public string TestFor { get; set; }
        public string TestItem { get; set; }
        public double Rate { get; set; }
        public double Upcharge { get; set; }
        public double UpchargeAmout { get; set; }
        public double NetRate { get; set; }
        public int Currency { get; set; }
        public int TestingCompany { get; set; }
    }
}
