//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineEntry
    {
        public int Id { get; set; }
        public int Company { get; set; }
        public string Attachment { get; set; }
        public int Location { get; set; }
        public Nullable<int> ProdCapacity { get; set; }
        public int FloorNo { get; set; }
        public int CapacityUOMId { get; set; }
        public string MachineNo { get; set; }
        public string Brand { get; set; }
        public string Category { get; set; }
        public string Origin { get; set; }
        public string Group { get; set; }
        public string PurchaseDate { get; set; }
        public Nullable<int> DiaWidth { get; set; }
        public Nullable<int> PurchaseCost { get; set; }
        public string Gauge { get; set; }
        public Nullable<int> AccumulatedDep { get; set; }
        public string ExtraCylinder { get; set; }
        public Nullable<int> DepreciationRate { get; set; }
        public string Nooffeeder { get; set; }
        public string DepreciationMethod { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string Status { get; set; }
    }
}
