//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailRecipientGroup
    {
        public int Id { get; set; }
        public int CompanyName { get; set; }
        public string MailItem { get; set; }
        public string YouHaveSelected { get; set; }
        public string Status { get; set; }
    }
}
