//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuSubSub
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int ParentMenuMainId { get; set; }
        public int ParentOrMenuSubId { get; set; }
        public string Link { get; set; }
        public string Icon { get; set; }
        public bool Visibility { get; set; }
        public string UserId { get; set; }
        public int SubSubMenuId { get; set; }
        public bool Save { get; set; }
        public bool Edit { get; set; }
        public bool Delete { get; set; }
        public bool Approve { get; set; }
    }
}
