//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferingCostCostingSheet
    {
        public int Id { get; set; }
        public double OrderQty { get; set; }
        public double OrderQtyPrice { get; set; }
        public double ShipmentQty { get; set; }
        public double ShipmentQtyPrice { get; set; }
        public double ShortORExtra { get; set; }
        public double ShortORExtraPrice { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
        public Nullable<double> DollerRate { get; set; }
        public Nullable<int> FileNo { get; set; }
    }
}
