//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferingCostBuyerInformation
    {
        public int Id { get; set; }
        public int OrderAutoId { get; set; }
        public int OfferingCostId { get; set; }
        public string BuyingHouse { get; set; }
        public string Customer { get; set; }
        public string Item { get; set; }
        public string StyleNo { get; set; }
        public string SizeRangeStart { get; set; }
        public string SizeRangeEnd { get; set; }
        public string Costing { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
