//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherPartyProfile
    {
        public int Id { get; set; }
        public string OtherPartyName { get; set; }
        public string ShortName { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public int CountryNameId { get; set; }
        public string Designation { get; set; }
        public string Remark { get; set; }
        public string ContactNo { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public string URLName { get; set; }
        public string ImageName { get; set; }
        public string ImagePathName { get; set; }
    }
}
