//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBankLoan
    {
        public int Id { get; set; }
        public Nullable<int> Particular { get; set; }
        public string LDNo { get; set; }
        public Nullable<decimal> ActualInterest { get; set; }
        public Nullable<decimal> InterestRebet { get; set; }
        public Nullable<decimal> TotalInterestRebet { get; set; }
        public Nullable<decimal> ActualPayment { get; set; }
        public Nullable<System.DateTime> LoanReDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> LdNoId { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    }
}
