//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PiAcceptance
    {
        public int Id { get; set; }
        public string PiNumber { get; set; }
        public int PiMasterId { get; set; }
        public int AcptnceMasterId { get; set; }
        public string ItemCategory { get; set; }
        public Nullable<double> PiValue { get; set; }
        public Nullable<double> CurrAcptncValue { get; set; }
        public Nullable<double> CummulAcptncValue { get; set; }
        public Nullable<double> NetMrrValue { get; set; }
        public Nullable<double> Balance { get; set; }
    }
}
