//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PiDetail
    {
        public int Id { get; set; }
        public int GetExportPI { get; set; }
        public int ItemCategoryId { get; set; }
        public string Importer { get; set; }
        public int SupplierProfileId { get; set; }
        public string PiNo { get; set; }
        public string PiDate { get; set; }
        public string LastShipmentDate { get; set; }
        public string PiValidityDate { get; set; }
        public int CurrencyId { get; set; }
        public string Source { get; set; }
        public string HsCode { get; set; }
        public int InternalFileNo { get; set; }
        public string IndentorName { get; set; }
        public string PiBasis { get; set; }
        public string GoodsRcvStatus { get; set; }
        public double LcGroupNo { get; set; }
        public string Remarks { get; set; }
        public string ReadyToApproved { get; set; }
        public string RequestedBy { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
