//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PiEntryFromWo
    {
        public int Id { get; set; }
        public int PiMasterId { get; set; }
        public int ItemCategoryId { get; set; }
        public int WorkOrderId { get; set; }
        public int WorkOrderChildId { get; set; }
        public string WorkOrderNo { get; set; }
        public string HsCode { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public string ItemGroup { get; set; }
        public string ItemDescription { get; set; }
        public string BrandOrSuppRef { get; set; }
        public string GmtsColor { get; set; }
        public string GmtsSize { get; set; }
        public string ItemColor { get; set; }
        public string ItemSize { get; set; }
        public string GmtsItem { get; set; }
        public string BodyPart { get; set; }
        public string Gsm { get; set; }
        public string DiaOrWidth { get; set; }
        public string Count { get; set; }
        public string Composition { get; set; }
        public string YarnType { get; set; }
        public string ColorRange { get; set; }
        public string Lot { get; set; }
        public Nullable<double> Percentage { get; set; }
        public string ServiceType { get; set; }
        public string RdNo { get; set; }
        public string Weight { get; set; }
        public string WeightType { get; set; }
        public string Width { get; set; }
        public string CutableWidth { get; set; }
        public string UOM { get; set; }
        public double Quantity { get; set; }
        public double Rate { get; set; }
        public double Amount { get; set; }
        public string Status { get; set; }
        public double Upcharge { get; set; }
        public double Discount { get; set; }
        public double Total { get; set; }
        public double NetTotal { get; set; }
        public string EntryDate { get; set; }
        public int EntryBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ApprovedDate { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
    }
}
