//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreCosting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreCosting()
        {
            this.YarnCostPreCostings = new HashSet<YarnCostPreCosting>();
        }
    
        public int PrecostingId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string CostingDate { get; set; }
        public string Incoterm { get; set; }
        public string IncotermPlace { get; set; }
        public string PoId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<int> QuotationId { get; set; }
        public Nullable<int> ApprovedId { get; set; }
        public Nullable<int> currencyId { get; set; }
        public Nullable<int> jobQty { get; set; }
        public Nullable<int> companyId { get; set; }
        public Nullable<int> orderUOMId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> BudgetMinuite { get; set; }
        public Nullable<double> eR { get; set; }
        public Nullable<double> CutSMV { get; set; }
        public Nullable<double> CutEfficiency { get; set; }
        public Nullable<double> SewSMV { get; set; }
        public Nullable<double> SewEfficiency { get; set; }
        public string StyleRef { get; set; }
        public string StyleDesc { get; set; }
        public string Remark { get; set; }
        public string agent { get; set; }
        public string machineLine { get; set; }
        public string prodLineHr { get; set; }
        public string ReadyToApproved { get; set; }
        public string imagesPath { get; set; }
        public string Fileno { get; set; }
        public string internalRef { get; set; }
        public string CopyFrom { get; set; }
        public string Unapproverequest { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<double> CostingPer { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public string ApprovalDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YarnCostPreCosting> YarnCostPreCostings { get; set; }
    }
}
