//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionFloor
    {
        public int Id { get; set; }
        public int Company { get; set; }
        public int Location { get; set; }
        public int Floor { get; set; }
        public int FloorSequence { get; set; }
        public int ProductionProcessId { get; set; }
        public string Status { get; set; }
    }
}
