//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplacementLCForm
    {
        public int Id { get; set; }
        public int ExportLCMasterId { get; set; }
        public int SalesContractMasterId { get; set; }
        public string SalesContract { get; set; }
        public Nullable<double> ReplacedAmount { get; set; }
        public Nullable<double> ContractValue { get; set; }
        public Nullable<double> CumulativeReplaced { get; set; }
        public Nullable<double> YettoReplace { get; set; }
        public string AttachedBTBLC { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
