//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiredAccessory
    {
        public int Id { get; set; }
        public string SampleName { get; set; }
        public int GarmentsItemId { get; set; }
        public int TrimsGroupId { get; set; }
        public int SupplierProfileId { get; set; }
        public string BrandOrSuppRef { get; set; }
        public string Description { get; set; }
        public int SampleFabricBookingid { get; set; }
        public int OrderId { get; set; }
        public int SampleRequisitionId { get; set; }
        public int Uom { get; set; }
        public string ReqDzn { get; set; }
        public double ReqQty { get; set; }
        public string AccDelDate { get; set; }
        public string AccSource { get; set; }
        public string Remarks { get; set; }
        public string Image { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
