//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RollwiseGreyFabricSampleToOrderDetail
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public int Sl { get; set; }
        public string BarcodeNo { get; set; }
        public string RollNo { get; set; }
        public string ProgramNo { get; set; }
        public string ProductId { get; set; }
        public string FabricDescription { get; set; }
        public string YoRCount { get; set; }
        public string YoRBrand { get; set; }
        public string YoRLot { get; set; }
        public string Rack { get; set; }
        public string Shelf { get; set; }
        public string StitchLength { get; set; }
        public string RollWgt { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
