//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesForecastEntryDetail
    {
        public int Id { get; set; }
        public string Month { get; set; }
        public int Year { get; set; }
        public int SalesForecastMasterId { get; set; }
        public int CYQntyTarget { get; set; }
        public int CYValueTarget { get; set; }
        public int CYTargetMint { get; set; }
        public int PYQntyTarget { get; set; }
        public int PYValueTarget { get; set; }
        public int PYTargetMint { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string Status { get; set; }
    }
}
