//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesForecastEntry
    {
        public int Id { get; set; }
        public int BuyerId { get; set; }
        public int AgentId { get; set; }
        public int TeamLeaderId { get; set; }
        public string Designation { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string Status { get; set; }
    }
}
