//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleDevelopmentEntry
    {
        public int Id { get; set; }
        public int SampleTypeId { get; set; }
        public string SampleColor { get; set; }
        public string RcvDateFromBuyer { get; set; }
        public string TfReceivDate { get; set; }
        public string BuyerDeadLine { get; set; }
        public string WorkingFactory { get; set; }
        public string SentToSmplDept { get; set; }
        public string DeadLine { get; set; }
        public string RcvFromSmplDept { get; set; }
        public string Fabrication { get; set; }
        public string FabricSource { get; set; }
        public string SentToBuyer { get; set; }
        public string KeyPointOrValDrive { get; set; }
        public string Department { get; set; }
        public string ApprovalStatus { get; set; }
        public string StatusDate { get; set; }
        public string BuyerMeeting { get; set; }
        public string SampleCharge { get; set; }
        public string BuyerReqNo { get; set; }
        public string Comments { get; set; }
        public string Currency { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string Status { get; set; }
    }
}
