//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleFabricBookingWithorder
    {
        public int Id { get; set; }
        public string BookingNo { get; set; }
        public int BuyerProfileId { get; set; }
        public string Month { get; set; }
        public int Year { get; set; }
        public int FabricNature { get; set; }
        public string FabricSource { get; set; }
        public string BookingDate { get; set; }
        public string OrderNo { get; set; }
        public string Currency { get; set; }
        public double ExchangeRate { get; set; }
        public string Source { get; set; }
        public string DeliveryDate { get; set; }
        public string PayMode { get; set; }
        public int SupplierProfileId { get; set; }
        public string Attention { get; set; }
        public string ReadyToApproved { get; set; }
        public string FabricComposition { get; set; }
        public string FileNo { get; set; }
        public string RefNo { get; set; }
        public string TagBookingNo { get; set; }
        public string Accessories { get; set; }
        public string TermsNcondition { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
