//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBookingForKnitingandDyeingWithoutOrder
    {
        public int Id { get; set; }
        public string WONo { get; set; }
        public int CompanyNameId { get; set; }
        public string FabBookingNo { get; set; }
        public int BuyerNameId { get; set; }
        public string BookingDate { get; set; }
        public int CurrencyId { get; set; }
        public double ExchangeRate { get; set; }
        public string PayMode { get; set; }
        public string Source { get; set; }
        public string KnitDyeSource { get; set; }
        public int SupplierNameId { get; set; }
        public string Attention { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
