//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBookingAllMasterDtl
    {
        public int Id { get; set; }
        public string BookingNo { get; set; }
        public Nullable<int> BuyerProfileId { get; set; }
        public int CurrencyId { get; set; }
        public int ExchangeRate { get; set; }
        public string BookingDate { get; set; }
        public string DeliveryDate { get; set; }
        public string PayMode { get; set; }
        public string Source { get; set; }
        public Nullable<int> SupplierProfileId { get; set; }
        public string ReadyToApproved { get; set; }
        public string Attention { get; set; }
        public int ProcessId { get; set; }
        public string WithMaterials { get; set; }
        public string KnitDyeSource { get; set; }
        public string JobOrPoLevel { get; set; }
        public string ShortOrNot { get; set; }
        public string FabricNature { get; set; }
        public string Sensitivity { get; set; }
        public string Remark { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string Status { get; set; }
        public Nullable<int> ApproveById { get; set; }
        public string ApproveDate { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
    }
}
