//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SewingThredConsumption
    {
        public int Id { get; set; }
        public Nullable<double> ConsPerGarment { get; set; }
        public Nullable<double> CostingPerDzn { get; set; }
        public Nullable<double> ConsLenth { get; set; }
        public Nullable<double> Cone { get; set; }
        public int TrimsCostId { get; set; }
    }
}
