//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SewingLine
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int LocationId { get; set; }
        public int FloorId { get; set; }
        public int SewingLineSequence { get; set; }
        public string LineName { get; set; }
        public string SewingGroup { get; set; }
        public string Status { get; set; }
    }
}
