//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SewingOperationForWorkStudy
    {
        public int Id { get; set; }
        public string ProductDept { get; set; }
        public int GarmentsItemId { get; set; }
        public int BodyPartId { get; set; }
        public string Code { get; set; }
        public string OperationName { get; set; }
        public double Rate { get; set; }
        public int FabricTypeId { get; set; }
        public string SmvBasis { get; set; }
        public double SeamLength { get; set; }
        public double MachineSMV { get; set; }
        public double ManualSMV { get; set; }
        public string DepartmentCode { get; set; }
        public int UomId { get; set; }
        public string Action { get; set; }
        public int ResourceId { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
