//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SewingOperation
    {
        public int Id { get; set; }
        public string Operation { get; set; }
        public int Rate { get; set; }
        public int UOMId { get; set; }
        public int ResourceId { get; set; }
        public Nullable<int> OperatorSMV { get; set; }
        public Nullable<int> HelperSMV { get; set; }
        public Nullable<int> TotalSMV { get; set; }
        public string Action { get; set; }
    }
}
