//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareholderShareDetail
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string NoOfShare { get; set; }
        public string FaceValue { get; set; }
        public string Premium { get; set; }
        public string ShareValue { get; set; }
        public int ShareholderId { get; set; }
    }
}
