//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shareholder
    {
        public int Id { get; set; }
        public string IdNo { get; set; }
        public string Name { get; set; }
        public string BoAccountId { get; set; }
        public string MothersName { get; set; }
        public string Profession { get; set; }
        public string Organization { get; set; }
        public string Designation { get; set; }
        public string NationalId { get; set; }
        public string Tin { get; set; }
        public string Vat { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Status { get; set; }
        public string PlotNoPr { get; set; }
        public string LevelNoPr { get; set; }
        public string RoadNoPr { get; set; }
        public string BlockNoPr { get; set; }
        public int CountryIdPr { get; set; }
        public string ProvincePr { get; set; }
        public string CityOrTownPr { get; set; }
        public string ZipCodePr { get; set; }
        public string PlotNoPe { get; set; }
        public string LevelNoPe { get; set; }
        public string RoadNoPe { get; set; }
        public string BlockNoPe { get; set; }
        public int CountryIdPe { get; set; }
        public string ProvincePe { get; set; }
        public string CityOrTownPe { get; set; }
        public string ZipCodePe { get; set; }
    }
}
