//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SizePannelPodetail
    {
        public int SizePannelId { get; set; }
        public Nullable<int> InputPannelId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> PoId { get; set; }
        public string ArticleNumber { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public Nullable<double> Quanity { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Status { get; set; }
        public Nullable<double> PlanCutQty { get; set; }
        public Nullable<double> ExcessCut { get; set; }
        public Nullable<double> Amount { get; set; }
        public bool BarCode { get; set; }
    }
}
