//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suplier
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string CompanyName { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersionDesignation { get; set; }
        public string SuplierType { get; set; }
        public Nullable<int> SuplyItemId { get; set; }
        public string Nominated { get; set; }
    }
}
