//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierProfile
    {
        public int Id { get; set; }
        public string SupplierName { get; set; }
        public string ShortName { get; set; }
        public string ContactPerson { get; set; }
        public string Designation { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string HttpWww { get; set; }
        public string AddressOne { get; set; }
        public string AddressTwo { get; set; }
        public string AddressThree { get; set; }
        public string AddressFour { get; set; }
        public string CountryId { get; set; }
        public string PartyTypeIds { get; set; }
        public string TagCompany { get; set; }
        public string LinkToBuyer { get; set; }
        public int CreditLimitDays { get; set; }
        public int CrditLimitAmount { get; set; }
        public string CrditLimitAmountType { get; set; }
        public int DiscountMethod { get; set; }
        public string SecuirityDeducted { get; set; }
        public string VatToBeDeducted { get; set; }
        public string AitToBeDeducted { get; set; }
        public string Remark { get; set; }
        public string Individual { get; set; }
        public string Status { get; set; }
        public string SupplierNature { get; set; }
        public string Image { get; set; }
        public string TagBuyer { get; set; }
        public string SupplierRef { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public string EntryDate { get; set; }
    }
}
