//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInitialOrder
    {
        public int OrderAutoID { get; set; }
        public string JobNo { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public string Style_Ref { get; set; }
        public string Style_Description { get; set; }
        public Nullable<int> Prod_DeptID { get; set; }
        public Nullable<int> Sub_DeptID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> Product_CatID { get; set; }
        public Nullable<int> Team_Leader_ID { get; set; }
        public Nullable<int> Dealing_Merchant_ID { get; set; }
        public string BH_Merchant { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Shipment_Mode_ID { get; set; }
        public int Order_Uom_ID { get; set; }
        public double SMV { get; set; }
        public Nullable<int> Packing_ID { get; set; }
        public Nullable<int> Season_ID { get; set; }
        public Nullable<int> Agent_ID { get; set; }
        public int UserID { get; set; }
        public string Repeat_No_Job { get; set; }
        public string Order_Number { get; set; }
        public string OrderImagePath { get; set; }
        public Nullable<int> factory_merchant { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<double> AvgUnitPrice { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> JobQuantity { get; set; }
    }
}
