//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductionDeptInfo
    {
        public int ID { get; set; }
        public string ProdDeptName { get; set; }
        public Nullable<int> Department_Id { get; set; }
    }
}
