//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermsNConditionSubTable
    {
        public int Id { get; set; }
        public int TermsNConditionId { get; set; }
        public int PageId { get; set; }
        public string PageNames { get; set; }
    }
}
