//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNATaskEntry
    {
        public int Id { get; set; }
        public int TaskNameId { get; set; }
        public string TaskShortName { get; set; }
        public string Penalty { get; set; }
        public int SequenceNo { get; set; }
        public Nullable<int> Completion { get; set; }
        public string GroupName { get; set; }
        public string Status { get; set; }
        public Nullable<int> GroupSeqNo { get; set; }
    }
}
