//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNATaskPercent
    {
        public int Id { get; set; }
        public int TaskNameId { get; set; }
        public int BuyerNameId { get; set; }
        public double StartPercent { get; set; }
        public double NoticeBefore { get; set; }
        public double EndPercent { get; set; }
        public string Status { get; set; }
    }
}
