//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrimsMeasurmentAllItemGroup
    {
        public int Id { get; set; }
        public Nullable<double> PerAccessories { get; set; }
        public Nullable<double> PerPcs { get; set; }
        public Nullable<double> PerDzn { get; set; }
        public Nullable<double> Lenth { get; set; }
        public Nullable<double> RequiredAccessories { get; set; }
        public int PrecostingId { get; set; }
        public Nullable<int> TrimsIndexId { get; set; }
        public Nullable<int> ConsIndexId { get; set; }
        public Nullable<int> ItemGroupId { get; set; }
        public string ItemGroupName { get; set; }
    }
}
