//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrimCost
    {
        public int Id { get; set; }
        public int PrecostingId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Description { get; set; }
        public string BrandSupRef { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> NominatedSuppId { get; set; }
        public Nullable<int> ConsUOMId { get; set; }
        public Nullable<double> ConsUnitGmts { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> TotalQty { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string ApvlReq { get; set; }
        public bool IsTrimBookingComplete { get; set; }
        public string ImagePath { get; set; }
        public Nullable<long> IndexNo { get; set; }
        public string ReportType { get; set; }
    }
}
