//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMapping
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int EmpCategoryId { get; set; }
        public int DepartmentId { get; set; }
        public int DesignationId { get; set; }
        public int AdditionDesignationId { get; set; }
        public string UnitName { get; set; }
        public int BuyerId { get; set; }
        public string DataLevelSecurity { get; set; }
        public string HomeGraph { get; set; }
        public string BindtoIP { get; set; }
        public string ExpiryDate { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
    }
}
