//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableSettingsTable
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int ModuleId { get; set; }
        public int CountPageInputField { get; set; }
        public int VariableListId { get; set; }
        public string LabelOne { get; set; }
        public string ValueOne { get; set; }
        public string LabelTwo { get; set; }
        public string ValueTwo { get; set; }
        public string LabelThree { get; set; }
        public string ValueThree { get; set; }
        public string LabelFour { get; set; }
        public string ValueFour { get; set; }
        public string LabelFive { get; set; }
        public string ValueFive { get; set; }
        public string LabelSix { get; set; }
        public string ValueSix { get; set; }
        public string LabelSeven { get; set; }
        public string ValueSeven { get; set; }
    }
}
