//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BankLoan
    {
        public string ParticularValue { get; set; }
        public int Id { get; set; }
        public Nullable<int> Particular { get; set; }
        public string BankRef { get; set; }
        public string LDNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> BankRefId { get; set; }
        public Nullable<int> EntryBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> GivenPaymentDay { get; set; }
        public Nullable<decimal> GivenInterestRebet { get; set; }
        public Nullable<decimal> DuePayment { get; set; }
    }
}
