//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PartialFabricBookingItemDtlsChilds
    {
        public Nullable<int> OrderAutoID { get; set; }
        public string jobNO { get; set; }
        public int Id { get; set; }
        public int PreCostingId { get; set; }
        public int PoNoId { get; set; }
        public int PartialFabricBookingMasterId { get; set; }
        public int FabricCostId { get; set; }
        public int BodyPartId { get; set; }
        public int ColorTypeId { get; set; }
        public string WidthDiaType { get; set; }
        public int FabricDesPreCostId { get; set; }
        public string FabricDescription { get; set; }
        public double GsmWeight { get; set; }
        public string GmtsColor { get; set; }
        public string ItemColor { get; set; }
        public string CnsmtnEntryDia { get; set; }
        public double CnsmtnEntryProcess { get; set; }
        public double BalanceQty { get; set; }
        public double WoQnty { get; set; }
        public double AdjQnty { get; set; }
        public double AcWoQnty { get; set; }
        public string Uom { get; set; }
        public double Rate { get; set; }
        public double Amount { get; set; }
    }
}
