//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WovenFinishFabricRollIssueDetail
    {
        public int Id { get; set; }
        public string MasterId { get; set; }
        public string Sl { get; set; }
        public string BarcodeNo { get; set; }
        public string RollNo { get; set; }
        public string BatchNo { get; set; }
        public string ProductId { get; set; }
        public string GmtItem { get; set; }
        public string BodyPart { get; set; }
        public string ConstructionByComposition { get; set; }
        public string Dia { get; set; }
        public string Color { get; set; }
        public string RollWgt { get; set; }
        public string Buyer { get; set; }
        public string JobNo { get; set; }
        public string OrderNo { get; set; }
        public string ProgramByBookingByPINo { get; set; }
        public string Basis { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
