//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WovenFinishFabricRollIssue
    {
        public int Id { get; set; }
        public string IssueNo { get; set; }
        public int CompanyId { get; set; }
        public string ServiceSource { get; set; }
        public int ServiceCompany { get; set; }
        public string IssueDate { get; set; }
        public string IssuePurpose { get; set; }
        public string BatchNo { get; set; }
        public string ReqsnNo { get; set; }
        public string RollNumber { get; set; }
        public string StoreName { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
