//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarnIssue
    {
        public int Id { get; set; }
        public string SystemID { get; set; }
        public int CompanyId { get; set; }
        public string Basis { get; set; }
        public string IssuePurpose { get; set; }
        public string IssueDate { get; set; }
        public string FabBookingNo { get; set; }
        public string KnittingSource { get; set; }
        public string IssueTo { get; set; }
        public int LocationId { get; set; }
        public int SupplierId { get; set; }
        public string ChallanOrProgramNo { get; set; }
        public string LoanParty { get; set; }
        public int SampleId { get; set; }
        public int BuyerId { get; set; }
        public string StyleReference { get; set; }
        public string BuyerJobNo { get; set; }
        public string Remarks { get; set; }
        public string ReadytoApprove { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
