//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarnPurchaseRequisition
    {
        public int Id { get; set; }
        public string RequisitionNo { get; set; }
        public int ItemCategoryId { get; set; }
        public string RequiredDate { get; set; }
        public string PayMode { get; set; }
        public string RequisitionDate { get; set; }
        public int CurrencyId { get; set; }
        public string Source { get; set; }
        public string DoNo { get; set; }
        public string Attention { get; set; }
        public string DealingMerchant { get; set; }
        public string PiBasis { get; set; }
        public string ReadytoApprove { get; set; }
        public string Remarks { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
