//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarnCountDeterminationChild
    {
        public int Id { get; set; }
        public int CompositionId { get; set; }
        public double Percentage { get; set; }
        public int YarnCountId { get; set; }
        public string Type { get; set; }
        public int YarnCountDeterminationMasterId { get; set; }
    }
}
