//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarnConsOptimaizationStripeColor
    {
        public int Id { get; set; }
        public int StripeColorId { get; set; }
        public int CompositionId { get; set; }
        public double Percentage { get; set; }
        public Nullable<double> Cons { get; set; }
    }
}
