//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarnPurchaseRequisitionDetail
    {
        public int Id { get; set; }
        public int YarnPurchaseRequisitionId { get; set; }
        public string JobNo { get; set; }
        public string FabBooking { get; set; }
        public int BuyerProfileId { get; set; }
        public string Style { get; set; }
        public string YarnColor { get; set; }
        public int YarnCountId { get; set; }
        public int CompositionId { get; set; }
        public int Percentage { get; set; }
        public int YarnTypeId { get; set; }
        public int UomId { get; set; }
        public double RequisitionQty { get; set; }
        public double Rate { get; set; }
        public double Amount { get; set; }
        public string YarnInhouseDate { get; set; }
        public string Remarks { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string Status { get; set; }
    }
}
