//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarnCost
    {
        public int Id { get; set; }
        public int CountId { get; set; }
        public int Comp1Id { get; set; }
        public int precostingId { get; set; }
        public double percentage { get; set; }
        public string Color { get; set; }
        public int TypeId { get; set; }
        public Nullable<float> ConsQnty { get; set; }
        public int SupplierId { get; set; }
        public float Rate { get; set; }
        public float Amount { get; set; }
        public bool IsBookingComplete { get; set; }
        public Nullable<int> FabricCostId { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> ColorTypeId { get; set; }
        public Nullable<bool> isLoadFromStripeClr { get; set; }
        public Nullable<int> StripeClrId { get; set; }
        public Nullable<int> FabricIndexNo { get; set; }
        public Nullable<int> FabricDescId { get; set; }
        public Nullable<int> YrnCnsStrpId { get; set; }
        public string BodyColor { get; set; }
    }
}
