//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarnCostPreCosting
    {
        public int Id { get; set; }
        public Nullable<int> PreCostingId { get; set; }
        public Nullable<int> CountId { get; set; }
        public Nullable<int> Comp1Id { get; set; }
        public Nullable<double> Percent { get; set; }
        public Nullable<int> YarnTypeId { get; set; }
        public Nullable<double> ConsQnty { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Amont { get; set; }
    
        public virtual PreCosting PreCosting { get; set; }
        public virtual YarnComp1 YarnComp1 { get; set; }
        public virtual YarnCount YarnCount { get; set; }
        public virtual YarnType YarnType { get; set; }
    }
}
