//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarnBagStickerChild
    {
        public int Id { get; set; }
        public string Lot { get; set; }
        public int Count { get; set; }
        public int Composition { get; set; }
        public double Percentage { get; set; }
        public string YarnType { get; set; }
        public string Color { get; set; }
        public string Brand { get; set; }
        public double NoofBag { get; set; }
        public double WgtOrCone { get; set; }
        public double ConeOrBag { get; set; }
        public double BagWgt { get; set; }
        public double RateOrPerUnit { get; set; }
        public int YarnBagStickerMasterId { get; set; }
        public string Status { get; set; }
        public string EntryDate { get; set; }
        public string EntryBy { get; set; }
        public string ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ModifyiedDate { get; set; }
        public bool IsModifyied { get; set; }
        public string ModifyiedBy { get; set; }
    }
}
